spring:
  datasource:
    url: jdbc:mysql://localhost:3306/did
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost


# 区块链地址
block:
  req:
    host: https://ethereum-ropsten-rpc.allthatnode.com
  id: 83